### PR TITLE
fix: disable postgrest monitoring for the moment

### PR DESCRIPTION
**Pull request by darora**
This makes it substantially more straightforward to track customer
usage of the DB. We should re-enable this once we have a more
tractable path forward.

### CODE REVIEW

**Review by inian — APPROVED** [review]

**Comment by steve-chavez** [comment]
All postgrest queries start with `WITH pgrst_source AS (..)`, that could serve as a way to track postgrest usage at the db side.

There was also a discussion about appending `?application_name=postgrest` to its connection string, not sure if this is being done atm.

**Comment by darora** [comment]
@steve-chavez for this use case we need to differentiate between _customer_ usage and Supabase platform-internal usage. So the DB traffic generated by our monitoring services hitting the openapi spec endpoint needs to not be counted towards customer usage, while other postgrest traffic does.

This gets pretty messy because the openapi endpoint currently results in six entries in the pg_stat_statements view. It'd be great if those statements could be differentiated by either a different username, or some other similar characteristic.

https://www.notion.so/supabase/RFC-Shutdowns-v2-5ce8e9c7350f47be833a07f33fc45dc4

**Comment by darora** [comment]
or if it offered a separate, more minimal healthcheck endpoint that e.g. just executed a `select 1;` or `select version()` to ensure db health, that'd be awesome

**Comment by steve-chavez** [comment]
@darora Noted! Actually a minimal health check has already been requested https://github.com/PostgREST/postgrest/issues/1933. I'll prioritize this feature :+1: .

**Pull request merged**
